version: "3"

services:
  github_mirror:
    container_name: github_mirror
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - ./secrets.yaml:/srv/secrets.yaml:ro
        - ./data:/srv/repos
    environment:
        - BACKUP_DELAY_IN_SECONDS=3600 # 1 hour
        - LOG_LEVEL=INFO
        - TARGET_DIR=/srv/repos
    # command: tail -f /dev/null
    restart: always
